django_project/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('tracker/', include('study_bee.urls')),
    path('diary/', include('diary_tracker.urls')),
    path('forum/', include('forum.urls')),
]

main/urls.py
from django.urls import path

from main.views import *

app_name = 'main'

urlpatterns = [
    path('', home, name='home'),
]

study_bee/urls.py
from django.urls import path
from study_bee.views import show_planner, login_user, register, logout_user, add_plan, edit_plan, delete_plan #sesuaikan dengan nama fungsi yang dibuat



app_name = 'study_bee'

urlpatterns = [
    path('', show_planner, name='planner'),
    path('register/', register, name='register'), #sesuaikan dengan nama fungsi yang dibuat
    path('login/', login_user, name='login'), #sesuaikan dengan nama fungsi yang dibuat
    path('logout/', logout_user, name='logout'), #sesuaikan dengan nama fungsi yang dibuat
    path('planner/', show_planner, name='show_planner'),
    path('planner/add_plan/', add_plan, name='add_plan'),
    path('planner/edit_plan/<int:plan_id>/', edit_plan, name='edit_plan'),
    path('planner/delete_plan/<int:plan_id>/', delete_plan, name='delete_plan'),


]

study_bee/models.py
from time import timezone
from django.db import models
from django.utils import timezone

class StudyPlan(models.Model):
    TYPE_CHOICES = [
        ('group', 'Group'),
        ('individual', 'Individual'),
    ]
    
    name = models.CharField(max_length=50, default='')
    type = models.CharField(max_length=20, choices=TYPE_CHOICES, default='')
    subject = models.CharField(max_length=100, default='')
    date = models.DateField(default=timezone.now)
    location = models.CharField(max_length=200, default='')
    description = models.TextField(default='')

study_bee/forms.py
from django import forms
from django.utils.timezone import now
from .models import StudyPlan

class StudyPlanForm(forms.ModelForm):
    class Meta:
        model = StudyPlan
        fields = ['name', 'type', 'subject', 'date', 'location', 'description']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}, format='%Y-%m-%d'),
        }

    name = forms.CharField(
        max_length=50, 
        widget=forms.TextInput(attrs={'placeholder': 'Enter plan name', 'class': 'form-control'})
    )

    type = forms.ChoiceField(
        choices=StudyPlan.TYPE_CHOICES, 
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    subject = forms.CharField(
        max_length=100, 
        widget=forms.TextInput(attrs={'placeholder': 'Enter subject', 'class': 'form-control'})
    )

    date = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}, format='%Y-%m-%d'),
        initial=now()
    )

    location = forms.CharField(
        max_length=200, 
        widget=forms.TextInput(attrs={'placeholder': 'Enter location', 'class': 'form-control'})
    )

    description = forms.CharField(
        widget=forms.Textarea(attrs={'placeholder': 'Enter description', 'class': 'form-control'})
    )

study_bee/views.py
from time import timezone
from django.shortcuts import get_object_or_404, render, redirect
from study_bee.models import StudyPlan
from django.http import HttpResponseRedirect
from study_bee.forms import StudyPlanForm
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import datetime
from django.utils import timezone




# Create your views here.



def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('study_bee:login')

    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("study_bee:show_planner")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('study_bee:login'))
    response.delete_cookie('last_login')
    return response


@login_required(login_url='/study_bee/login/')
def show_planner(request):
    if request.method == 'POST':
        form = StudyPlanForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = StudyPlanForm()
    now = timezone.now()
    study_plans = StudyPlan.objects.all().order_by('-date')
    return render(request, 'planner.html', {'form': form, 'study_plans': study_plans, 'now': now})

def add_plan(request):
    if request.method == 'POST':
        form = StudyPlanForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('study_bee:planner'))
    else:
        form = StudyPlanForm()
    return render(request, 'add_plan.html', {'form': form})


def edit_plan(request, plan_id):
    study_plan = get_object_or_404(StudyPlan, pk=plan_id)

    if request.method == 'POST':
        form = StudyPlanForm(request.POST, instance=study_plan)
        if form.is_valid():
            form.save()
            return redirect('study_bee:planner')
    else:
        form = StudyPlanForm(instance=study_plan)

    return render(request, 'edit_plan.html', {'form': form, 'study_plan': study_plan})



def delete_plan(request, plan_id):
    plan = get_object_or_404(StudyPlan, pk=plan_id)
    if request.method == 'POST':
        plan.delete()
        return redirect('study_bee:planner')
    return render(request, 'delete_plan.html', {'plan': plan})

study_bee/templates/add_plan.html
{% extends 'base.html' %}

{% block content %}
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addPlanModalLabel">New Study Plan</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="post" action="{% url 'study_bee:add_plan' %}" onsubmit="submitButton.disabled = true; return true;">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="modal-footer">
                        <button type="submit" name="submitButton" class="btn btn-primary">Add Plan</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

study_bee/templates/delete_plan.html
{% extends 'base.html' %}

{% block content %}

<div class="modal-dialog" role="document">
    <div class="modal-content">
    <div class="modal-header">
        <h5 class="modal-title" id="deletePlanModalLabel">Delete Plan</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        Are you sure you want to delete this plan?
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <form method="POST" action="{% url 'study_bee:delete_plan' plan_id=study_plan.pk %}" class="d-inline">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Delete</button>
        </form>
    </div>
    </div>
</div>

{% endblock %}

study_bee/templates/edit_plan.html
{% extends 'base.html' %}

{% block content %}

<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="editPlanModalLabel">Edit Plan</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <form method="POST" action="{% url 'study_bee:edit_plan' plan_id=study_plan.pk %}">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Save</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

study_bee/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>

            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    Belum mempunyai akun? <a href="{% url 'study_bee:register' %}">Buat Akun</a>

</div>

{% endblock content %}

study_bee/templates/planner.html
{% extends 'base.html' %}

{% block content %}

    <head>
        <style>
            .btn-outline-secondary.delete:hover {
                color: #fff !important;
                background-color: red;
                border-color: red;
            }

        </style>
    </head>

    <nav class="navbar navbar-expand-lg navbar-light bg-light shadow">
        <div class="d-flex">
        <a class="navbar-brand ml-1 mr-2" href="#" style="color:#FFC107; text-shadow: 0px 1px 1px #000000">StudyBee</a>
        <ul class="navbar-nav">
            <li class="nav-item">
            <a class="nav-link" href="#">Planner</a>
            </li>
        </ul>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
            <a class="nav-link" href="#">Log out</a>
            </li>
        </ul>
        </div>
    </nav>

    <br>

    <div class="d-flex justify-content-center">
        <button type="button" class="btn btn-warning text-dark shadow" data-toggle="modal" data-target="#addPlanModal" style="background-color: #FFC107">Add a Plan</button>
    </div>
    
    <div class="modal fade" id="addPlanModal" tabindex="-1" role="dialog" aria-labelledby="addPlanModalLabel" aria-hidden="true">
        {% include 'add_plan.html' %}
    </div>

    <div class="container my-4">
        <div class="row row-cols-1 row-cols-md-2 row-cols-lg-4">
            {% for study_plan in study_plans %}
            <div class="col mb-4">
            <div class="card shadow">
                <div class="card-body">
                <h5 class="card-title">{{ study_plan.name }} <small class="text-muted">{{ study_plan.get_type_display }}</small></h5>
                <p class="card-text">{{ study_plan.subject }}</p>
                <p class="card-text">{{ study_plan.date }}</p>
                <p class="card-text">
                    {% if study_plan.date|date:'Ymd' < now|date:'Ymd' %}
                    <span style="color:red">outdated</span>
                    {% elif study_plan.date|date:'Ymd' == now|date:'Ymd' %}
                    <span style="color:blue">ongoing</span>
                    {% else %}
                    <span style="color:green">upcoming</span>
                    {% endif %}
                </p>
                <p class="card-text">{{ study_plan.location }}</p>
                <p class="card-text">{{ study_plan.description }}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                    <a href="{% url 'study_bee:edit_plan' plan_id=study_plan.pk %}" class="btn btn-sm btn-outline-secondary" data-toggle="modal" data-target="#editPlanModal{{ study_plan.pk }}">Edit</a>
                    <div class="modal fade" id="editPlanModal{{ study_plan.pk }}" tabindex="-1" role="dialog" aria-labelledby="editPlanModalLabel" aria-hidden="true">
                        {% include 'edit_plan.html' %}
                    </div>
        
                    <form method="POST" action="{% url 'study_bee:delete_plan' plan_id=study_plan.pk %}" class="d-inline">
                        {% csrf_token %}
                        <button type="button" class="btn btn-sm btn-outline-secondary delete" data-toggle="modal" data-target="#deletePlanModal{{ study_plan.pk }}">Delete</button>
                        <div class="modal fade" id="deletePlanModal{{ study_plan.pk }}" tabindex="-1" role="dialog" aria-labelledby="deletePlanModalLabel" aria-hidden="true">
                        {% include 'delete_plan.html' %}
                        </div>
                    </form>
                    </div>
                </div>
                </div>
            </div>
            </div>
            {% empty %}
            <p>No plan yet.</p>
            {% endfor %}
        </div>
    </div>
    

{% endblock %}

study_bee/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">

    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

study_bee/templates/tracker.html
{% extends 'base.html' %}

{% block content %}
<h5>Nama: </h5>
<p>Fill me!</p>

<h5>Sesi terakhir login: {{ last_login }}</h5>

<table>
    <tr>
        <th>Nama</th>
        <th>Jenis</th>
        <th>Jumlah</th>
        <th>Tanggal</th>
        <th>Deskripsi</th>
    </tr>
    {% for transaction in list_of_transactions %}
    <tr>
        <td>{{transaction.name}}</td>
        <td>{{transaction.type}}</td>
        <td>{{transaction.amount}}</td>
        <td>{{transaction.date}}</td>
        <td>{{transaction.description}}</td>
    </tr>
{% endfor %}
    {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
</table>

<br>
<a href="{% url 'study_bee:create_transaction' %}">
    <button>
        Transaksi Baru
    </button>
</a>

<a href="{% url 'study_bee:logout' %}">
    <button>
        Logout
    </button>
</a>


{% endblock content %}